[package]
name = "image_classifier"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
tch = { version = "0.16.0", features = ["download-libtorch"] }
ureq = { version = "2.9.7", features = ["json"] }
